// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { ThemeProvider } from "@/components/theme-provider"; // Assuming you have this set up

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SaaS.ui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          {/* The Navbar sits here, outside of the page content */}
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}