import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative min-h-screen overflow-x-hidden antialiased`}
      >
        {/* Animated gradient background */}
        <div className="fixed inset-0 -z-10">
          <div className="pointer-events-none absolute top-0 left-0 z-0 h-full w-full">
            {/* The Beam: Rotated, heavily blurred, gradient from corner */}
            <div className="absolute -top-[20%] -left-[20%] h-[150%] w-[80%] rotate-45 transform-gpu bg-linear-to-br from-amber-300/30 via-orange-100/5 to-transparent blur-[100px] dark:from-indigo-500/30 dark:via-purple-500/5 dark:to-transparent" />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
